name = "EmmysApp"
uuid = "673f4181-0c60-4da1-924e-eff4a2ac0a09"
authors = ["keith hazelton <kh@aktis.org>"]
version = "0.1.0"

[deps]
Toolips = "a47e2ad8-fcf7-417c-9746-32b9bdf220bd"

[compat]
Toolips = "0.3"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]