name = "AppliedCategoryTheoryDDD"
uuid = "f14415da-f3c0-4c0b-aa99-6d77d83086b0"
authors = ["Your Name <your.email@example.com>"]
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]